-- Migration: Create rto_contracts table for Rent-to-Own contracts (Anexo 3)
-- Date: 2026-01-21
-- Description: Stores all RTO contracts generated by IncorporarAgent

-- Create rto_contracts table
CREATE TABLE IF NOT EXISTS rto_contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Parties
    client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    
    -- Contract Terms
    lease_term_months INTEGER NOT NULL CHECK (lease_term_months IN (24, 36, 48)),
    monthly_rent NUMERIC NOT NULL DEFAULT 0,
    down_payment NUMERIC DEFAULT 0,
    purchase_option_price NUMERIC DEFAULT 0,
    
    -- Dates
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    
    -- Payment Terms
    payment_day INTEGER DEFAULT 15 CHECK (payment_day >= 1 AND payment_day <= 28),
    late_fee_per_day NUMERIC DEFAULT 15.0,
    nsf_fee NUMERIC DEFAULT 250.0,
    
    -- Property Info (denormalized for contract reference)
    hud_number TEXT,
    property_year INTEGER,
    
    -- Status
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'pending_signature', 'active', 'completed', 'cancelled', 'defaulted')),
    
    -- Contract Document
    contract_text TEXT,
    contract_pdf_url TEXT,
    
    -- Signatures
    client_signed_at TIMESTAMPTZ,
    landlord_signed_at TIMESTAMPTZ,
    
    -- Metadata
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_rto_contracts_client ON rto_contracts(client_id);
CREATE INDEX IF NOT EXISTS idx_rto_contracts_property ON rto_contracts(property_id);
CREATE INDEX IF NOT EXISTS idx_rto_contracts_status ON rto_contracts(status);

-- Add assigned_client_id to properties table (for reservations)
ALTER TABLE properties 
    ADD COLUMN IF NOT EXISTS assigned_client_id UUID REFERENCES clients(id);

-- Create process_logs table if not exists (for audit trail)
CREATE TABLE IF NOT EXISTS process_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type TEXT NOT NULL, -- 'client', 'property', 'contract', etc.
    entity_id UUID NOT NULL,
    process TEXT NOT NULL, -- 'ADQUIRIR', 'INCORPORAR', 'COMERCIALIZAR', etc.
    action TEXT NOT NULL, -- 'created', 'updated', 'contract_generated', etc.
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_process_logs_entity ON process_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_process_logs_process ON process_logs(process);

-- RLS Policies
ALTER TABLE rto_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE process_logs ENABLE ROW LEVEL SECURITY;

-- Service role full access
CREATE POLICY "Service role can manage rto_contracts"
    ON rto_contracts FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role can manage process_logs"
    ON process_logs FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Authenticated users can view
CREATE POLICY "Authenticated users can view rto_contracts"
    ON rto_contracts FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can view process_logs"
    ON process_logs FOR SELECT
    TO authenticated
    USING (true);

-- Comments
COMMENT ON TABLE rto_contracts IS 'Rent-to-Own contracts (Anexo 3) generated by IncorporarAgent';
COMMENT ON TABLE process_logs IS 'Audit trail for all process actions';
COMMENT ON COLUMN properties.assigned_client_id IS 'Client who has reserved this property';

