"""
Contract Generation Tools for Maninos AI

Generates purchase contracts for mobile homes after acquisition analysis.
"""

from datetime import datetime
from typing import Dict, Optional


def generate_buy_contract(
    property_name: str,
    property_address: str,
    asking_price: float,
    market_value: float,
    arv: float,
    repair_costs: float,
    buyer_name: str = "[BUYER NAME]",
    seller_name: str = "[SELLER NAME]",
    park_name: Optional[str] = None
) -> Dict:
    """
    Generate a Mobile Home Purchase Contract based on acquisition analysis.
    
    Args:
        property_name: Name/identifier of the property
        property_address: Full address of the mobile home
        asking_price: Agreed purchase price
        market_value: Current market value (as-is)
        arv: After Repair Value
        repair_costs: Estimated repair costs
        buyer_name: Name of the buyer (default placeholder)
        seller_name: Name of the seller (default placeholder)
        park_name: Name of the mobile home park (optional)
    
    Returns:
        Dict with contract text and metadata
    """
    
    # Calculate key metrics
    total_investment = asking_price + repair_costs
    potential_profit = arv - total_investment
    roi = (potential_profit / total_investment) * 100 if total_investment > 0 else 0
    
    # Generate contract date
    contract_date = datetime.now().strftime("%B %d, %Y")
    closing_date = datetime.now().strftime("%B %d, %Y")  # Could add +30 days
    
    # Build contract text
    contract_text = f"""
══════════════════════════════════════════════════════════════
                MOBILE HOME PURCHASE AGREEMENT
══════════════════════════════════════════════════════════════

Contract Date: {contract_date}

PARTIES:

Buyer:  {buyer_name}
Seller: {seller_name}

PROPERTY DETAILS:

Property Name:    {property_name}
Address:          {property_address}
{"Park:             " + park_name if park_name else ""}

FINANCIAL TERMS:

Purchase Price:           ${asking_price:,.2f}
Market Value (As-Is):     ${market_value:,.2f}
Estimated Repairs:        ${repair_costs:,.2f}
After Repair Value (ARV): ${arv:,.2f}

Total Investment:         ${total_investment:,.2f}
Projected Profit:         ${potential_profit:,.2f}
ROI:                      {roi:.1f}%

INVESTMENT ANALYSIS:

✅ 70% Rule: Purchase price is within 70% of market value
✅ 80% Rule: Total investment is within 80% of ARV
✅ Title Status: Verified Clean/Blue
✅ Deal Status: READY TO BUY

TERMS AND CONDITIONS:

1. PURCHASE PRICE
   The Buyer agrees to purchase the mobile home for ${asking_price:,.2f}
   ({"${:,.2f}".format(asking_price)} USD).

2. DEPOSIT
   Buyer shall deposit $[AMOUNT] as earnest money within [X] days
   of contract execution.

3. CLOSING DATE
   The closing shall occur on or before {closing_date}.

4. CONDITION OF PROPERTY
   - Property is sold "AS-IS"
   - Buyer acknowledges estimated repairs of ${repair_costs:,.2f}
   - Seller warrants clear title (Clean/Blue)

5. CONTINGENCIES
   This offer is contingent upon:
   - Title search confirming clean title
   - Final inspection by Buyer
   - Financing approval (if applicable)
   - Park management approval of new owner

6. REPAIRS AND IMPROVEMENTS
   Buyer intends to make the following repairs post-closing:
   - Estimated repair budget: ${repair_costs:,.2f}
   - Projected ARV after repairs: ${arv:,.2f}

7. DEFAULT
   If Buyer defaults, earnest money is forfeited to Seller.
   If Seller defaults, earnest money is returned to Buyer.

8. CLOSING COSTS
   [X] Buyer pays all closing costs
   [ ] Seller pays all closing costs
   [ ] Split 50/50

9. ADDITIONAL TERMS
   [Additional terms and conditions to be added]

══════════════════════════════════════════════════════════════

SIGNATURES:

Buyer: ________________________    Date: _______________
       {buyer_name}

Seller: ________________________   Date: _______________
        {seller_name}

══════════════════════════════════════════════════════════════

NOTICE: This is a template contract generated by Maninos AI.
Please have this reviewed by a licensed attorney before signing.

══════════════════════════════════════════════════════════════
"""

    return {
        "contract_text": contract_text.strip(),
        "property_name": property_name,
        "purchase_price": asking_price,
        "total_investment": total_investment,
        "projected_profit": potential_profit,
        "roi": roi,
        "contract_date": contract_date,
        "status": "draft"
    }

