'use client'

import React from 'react'
import { FileText, Download, AlertTriangle, CheckCircle2 } from 'lucide-react'

interface ContractViewerProps {
  contractText: string;
  propertyName: string;
  purchasePrice: number;
  totalInvestment: number;
  projectedProfit: number;
  roi: number;
}

export function ContractViewer({
  contractText,
  propertyName,
  purchasePrice,
  totalInvestment,
  projectedProfit,
  roi
}: ContractViewerProps) {

  const handlePrintPDF = () => {
      try {
          // Format contract for PDF
          const printContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>MANINOS AI - Purchase Agreement</title>
    <style>
        @media print {
            body { margin: 0; padding: 20px; }
        }
        body {
            font-family: 'Courier New', monospace;
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            color: #1e293b;
            line-height: 1.8;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #000;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0 0 10px 0;
            font-size: 18px;
            font-weight: bold;
        }
        .contract-body {
            white-space: pre-wrap;
            font-family: 'Courier New', monospace;
            margin: 20px 0;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #000;
            text-align: center;
            font-size: 9px;
            color: #64748b;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>MANINOS AI - MOBILE HOME PURCHASE AGREEMENT</h1>
        <p>Property: ${propertyName}</p>
        <p>Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    </div>

    <div class="contract-body">${contractText.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>

    <div class="footer">
        <p><strong>LEGAL NOTICE:</strong> This is a template contract generated by MANINOS AI.</p>
        <p>Must be reviewed by a licensed attorney before signing.</p>
    </div>
    
    <script>
        window.onload = function() {
            setTimeout(function() {
                window.print();
            }, 250);
        };
    </script>
</body>
</html>
      `;
          
          // Create blob and open in new tab (more reliable than document.write)
          const blob = new Blob([printContent], { type: 'text/html' });
          const url = URL.createObjectURL(blob);
          const printWindow = window.open(url, '_blank');
          
          // Clean up blob URL after window opens
          if (printWindow) {
              setTimeout(() => {
                  URL.revokeObjectURL(url);
              }, 1000);
          } else {
              alert('Please allow popups to print the contract.');
              URL.revokeObjectURL(url);
          }
      } catch (error) {
          console.error('Failed to open print dialog:', error);
          alert('Failed to open print dialog. Please try again.');
      }
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-lg overflow-hidden my-4 w-full">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 p-6 text-white">
            <div className="flex justify-between items-start">
                <div>
                    <div className="flex items-center gap-2 mb-2">
                        <FileText size={24} />
                        <h3 className="font-bold text-xl">Purchase Agreement</h3>
                    </div>
                    <p className="text-blue-100 text-sm">{propertyName}</p>
                </div>
                <button 
                    onClick={handlePrintPDF} 
                    className="bg-white text-blue-600 px-4 py-2 rounded-lg font-semibold text-sm hover:bg-blue-50 transition-colors flex items-center gap-2 shadow-md"
                >
                    <Download size={16} />
                    Save as PDF
                </button>
            </div>
        </div>

        {/* Investment Summary */}
        <div className="bg-slate-50 p-6 border-b border-slate-200">
            <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-4">Investment Summary</h4>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-white p-3 rounded-lg border border-slate-200">
                    <p className="text-xs text-slate-500 mb-1">Purchase Price</p>
                    <p className="text-lg font-bold text-slate-900">${purchasePrice.toLocaleString()}</p>
                </div>
                <div className="bg-white p-3 rounded-lg border border-slate-200">
                    <p className="text-xs text-slate-500 mb-1">Total Investment</p>
                    <p className="text-lg font-bold text-slate-900">${totalInvestment.toLocaleString()}</p>
                </div>
                <div className="bg-white p-3 rounded-lg border border-emerald-200">
                    <p className="text-xs text-emerald-600 mb-1">Projected Profit</p>
                    <p className="text-lg font-bold text-emerald-700">${projectedProfit.toLocaleString()}</p>
                </div>
                <div className="bg-white p-3 rounded-lg border border-blue-200">
                    <p className="text-xs text-blue-600 mb-1">ROI</p>
                    <p className="text-lg font-bold text-blue-700">{roi.toFixed(1)}%</p>
                </div>
            </div>

            {/* Deal Status Badges */}
            <div className="flex flex-wrap gap-2 mt-4">
                <div className="flex items-center gap-1 bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-xs font-semibold">
                    <CheckCircle2 size={14} />
                    70% Rule Passed
                </div>
                <div className="flex items-center gap-1 bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-xs font-semibold">
                    <CheckCircle2 size={14} />
                    80% Rule Passed
                </div>
                <div className="flex items-center gap-1 bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-xs font-semibold">
                    <CheckCircle2 size={14} />
                    Ready to Buy
                </div>
            </div>
        </div>

        {/* Contract Text */}
        <div className="p-6">
            <h4 className="text-sm font-bold text-slate-600 uppercase tracking-wide mb-3">Contract Document</h4>
            <div className="bg-slate-50 rounded-lg p-6 border border-slate-200 font-mono text-xs leading-relaxed whitespace-pre-wrap max-h-[600px] overflow-y-auto">
                {contractText}
            </div>
            <p className="text-xs text-slate-400 mt-2 text-center">Scroll to view full contract • Click "Save as PDF" to download</p>
        </div>

        {/* Legal Warning */}
        <div className="bg-amber-50 border-t-4 border-amber-400 p-6">
            <div className="flex items-start gap-3">
                <AlertTriangle className="text-amber-600 shrink-0 mt-0.5" size={20} />
                <div>
                    <h4 className="font-bold text-amber-900 text-sm mb-2">⚠️ LEGAL NOTICE</h4>
                    <p className="text-xs text-amber-800 leading-relaxed">
                        This is a <strong>DRAFT CONTRACT</strong> generated by AI. It <strong>MUST</strong> be reviewed by a licensed real estate attorney before signing. 
                        MANINOS AI does not provide legal advice. Signing any contract is at your own risk.
                    </p>
                </div>
            </div>
        </div>
    </div>
  );
}

